language:
    - c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         
script:
    - gcc -std=gnu99 -w -o foo -I./ tests/foo.c && ./foo
    - gcc -std=gnu99 -w -o dog -I./ tests/dog.c && ./dog

before_install:
    - eval "${MATRIX_EVAL}"
