matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         
script:
    - gcc -std=gnu99 -w -o test -I. tests/test.c
    - ./test
    - gcc -std=gnu99 -w -o foo -I. tests/foo/main.c
    - ./foo
    - gcc -std=gnu99 -w -o shape -I. tests/shape/main.c
    - ./shape
    - gcc -std=gnu99 -w -o animal -I. tests/animal/animal.c ./tests/animal/main.c
    - ./animal
    
language:
    - c

before_install:
    - eval "${MATRIX_EVAL}"
